name: Java CD Pipeline

on:
  push:
    branches: [ "develop" ]
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: AWS login and docker image pull and run
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          envs: GITHUB_SHA
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            echo "docker 로그인 성공"
            sudo docker stop $(sudo docker ps -aq)
            echo "현재 실행 중인 모든 Docker 컨테이너 중지"
            sudo docker rm -f $(sudo docker ps -qa)
            echo "모든 Docker 컨테이너 강제로 삭제"
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}//daeng-ggu-payment
            echo "docker pull 성공"
            sudo docker run -d -p 80:8081 ${{ secrets.DOCKERHUB_USERNAME }}//daeng-ggu-payment
            sudo docker image prune -f
            echo "사용하지 않는 Docker image 정리"
